### ISSUE TITLE
Phantom 'remote-desktop-connection' cask causes problems

### ISSUE THREAD

**Issue by kenahoo** [caskroom/homebrew-cask#33575]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

Several `brew cask` subcommands fail with complaints about a `remote-desktop-connection` cask.  For example:

```
[KenMacBook-2:~] % brew cask list
Error: No available Cask for remote-desktop-connection

[KenMacBook-2:~] % brew cask outdated
Error: No available Cask for remote-desktop-connection
```

I know that `remote-desktop-connection` is unsupported for newer versions of the OS - I just want to get rid of whatever stub is hanging around & preventing proper operation.

#### Output of your command with `--verbose --debug`

```
[KenMacBook-2:~] % brew --version
Homebrew 1.2.0-62-gf1d4c4be78
Homebrew/homebrew-core (git revision d05c1; last commit 2017-05-08)

[KenMacBook-2:~] % brew cask list --verbose --debug
Error: No available Cask for remote-desktop-connection/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:111:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:128:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:40:in `block in installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/scopes.rb:30:in `installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:63:in `list_installed'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/list.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:115:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:158:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:163:in `rescue in process'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `process'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:92:in `<main>'
```

#### Output of `brew cask doctor`

```
[KenMacBook-2:~] % brew cask doctor                
==> Homebrew-Cask Version
Homebrew-Cask 1.2.0-62-gf1d4c4be78
caskroom/homebrew-cask (git revision eca98; last commit 2017-05-08)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3617 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-boneyard (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-gui (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-python (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-science (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services (0 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-versions (0 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="~/.pyenv/shims:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:~/perl5/bin:~/git/utils/perl:~/git/utils/git:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/zsh"
```

**Comment by kenahoo** [comment]
BTW - this seems to be new behavior, I've been using Cask for several years and today is the first time I've seen this error.  I'm not sure which version of Cask was installed previously, but it wouldn't have been older than about a month or two, I think.

**Comment by miccal** [comment]
Please run the command:
```
cd "$(brew --repository)"; git fetch; git reset --hard origin/master; brew update
```
which should fix your issue.

**Comment by kenahoo** [comment]
Thanks.  Before I had a chance to see this, on a whim I did `mv /usr/local/Caskroom/remote-desktop-connection /tmp`, which seemed to get everything working again.

However, your `reset --hard` suggestion looks like it wouldn't actually work - I did test it:

```
[KenMacBook-2:/usr/local/Homebrew] [master] % mkdir -p /usr/local/Caskroom/remote-desktop-connection 
[KenMacBook-2:/usr/local/Homebrew] [master] % git fetch; git reset --hard origin/master; brew update;
HEAD is now at f1d4c4be78 Merge pull request #2607 from MikeMcQuaid/travis-ci-tweaks-2
Already up-to-date.
[KenMacBook-2:/usr/local/Homebrew] [master] % brew cask list                                         
Error: No available Cask for remote-desktop-connection
```

Guessing this is because the errant directory is in `/usr/local/Caskroom`, not `/usr/local/Homebrew`.

I'm also a little confused about the difference between `stable` and `master`, is there a reference in the docs somewhere?

**Comment by vitorgalvao** [comment]
> Guessing this is because the errant directory is in `/usr/local/Caskroom`, not `/usr/local/Homebrew`.

It’s not errant. It’s supposed to be there.

> I'm also a little confused about the difference between `stable` and `master`, is there a reference in the docs somewhere?  

`stable` is a [release](https://github.com/Homebrew/brew/releases) and `master` is the latest code from the repo.

Closing since it was solved.

**Comment by kenahoo** [comment]
If `/usr/local/Caskroom/remote-desktop-connection` is supposed to be there, what solution do you propose besides removing it?  Your `reset --hard` doesn't solve the issue.

**Comment by vitorgalvao** [comment]
> If `/usr/local/Caskroom/remote-desktop-connection` is supposed to be there

I meant `/usr/local/Caskroom` isn’t an errant directory. But I misread your comment, so was answering a different thing.

**Comment by kenahoo** [comment]
Ah, okay, good - we're in agreement then.  Thanks for the clarification!
