### ISSUE TITLE
`brew cask upgrade` breaks Launchpad shortcuts

### ISSUE THREAD

**Issue by wickles** [caskroom/homebrew-cask#42112]
#### General troubleshooting steps

- [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

The new function `brew cask upgrade` breaks the icon/link in Launchpad for the upgraded app(s). 

The icon becomes a question mark and the shortcut stops functioning; sometimes a new icon is placed in Launchpad for the updated app at the first open slot in addition to the broken icon. The broken icons might go away when rebooting, I'm not sure the exact behavior yet. 

This was never a problem with the unsupported old method I used before, `brew cask install --force <app_to_update>`, which seems to simply overwrites the old app in place. Is there a way to fix this with the new behavior?

![screen shot 2017-12-19 at 1 19 23 pm](https://user-images.githubusercontent.com/4229542/34177217-131cfa6a-e4c0-11e7-9634-9c6c77f235cd.png)

**Comment by commitay** [comment]
> The broken icons might go away when rebooting, I'm not sure the exact behavior yet

Can you please check if this is intermittent behaviour or not by reloading Launchpad (`killall Dock`) and rebooting?

**Comment by wickles** [comment]
Neither fixed the issue. Still see broken question mark icons. When I hold the Option key they show an X to delete like MAS apps.

**Comment by vitorgalvao** [comment]
@wickles What about `defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock`?

**Comment by wickles** [comment]
If I had known what it did I would have said it would obviously work. The bad icons are gone, and it completely reset all of my organization. Some warning would have been nice :/ Does it make a backup before resetting?

**Comment by vitorgalvao** [comment]
@wickles I don’t think it makes a backup, but if you have one (Time Machine), you might be able to recover the `~/Preferences/com.apple.dock.plist` and set it to what it was.

Apologies on undoing your configuration — I had only briefly looked at your screenshot when the issue was first posted and it looked roughly alphabetical (i.e. not organised).

In what sense are the bad icons gone? Are the icons for the apps themselves gone (unexpected) or are they fixed to what they should be (expected)?

**Comment by wickles** [comment]
Oh well. I guess this gives me the impetus to clean up unused apps anyway. 

All the upgraded apps now show up in Launchpad and work as expected. I tried upgrading a few more casks and am not seeing the same behavior anymore. I take it you haven't seen this behavior yourself then?

**Comment by commitay** [comment]
> I take it you haven't seen this behavior yourself then?

No, I haven't encountered this. Can you please post `brew cask doctor`? I'm mostly interested in your macOS version and that you are running the latest version of Homebrew.

**Comment by wickles** [comment]
Everything should be latest, except macOS which I haven't gotten around to updating the latest minor update 10.13.2 yet. 

```
> % brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.1-3-g426c998
caskroom/homebrew-cask (git revision 0b412a; last commit 2017-12-20)
==> macOS
10.13.1
==> Java
9.0.1, 9, 1.8.0_144, 1.8.0_131, 1.8.0_121, 1.8.0_112
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 140.2MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3865 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (137 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
Attempted to reproduce on `10.13.2` with `calibre` and `atom` without success.

**Comment by wickles** [comment]
I am still seeing similar behavior but only with Firefox now. After upgrade the firefox icon has a question mark over it (not blank like in previous screenshots), and there is no replacement icon.

**Comment by commitay** [comment]
Does `brew cask install --force firefox` fix it?

**Comment by wickles** [comment]
Hi. Sorry for the delay. I tried both of those the day this happened, and neither worked. I did an OS update and reboot since then and it seems fixed, Firefox is back in Launchpad since a few days ago. 

What would be the best way to experiment with this? Is there a simple way to rollback a single cask without rewinding the entire repo, so I can test some upgrades?

**Comment by commitay** [comment]
I can reproduce this with `docker`, however I ran `brew cask zap docker && brew cask install docker` and have a Launchpad icon the same as the top post.

**Comment by bpholt** [comment]
This happened to me today with the `intellij-idea-ce` cask. I also removed the broken icon by holding ⌥ and clicking the X on the icon and now the icon is gone from Launchpad altogether and won't come back, despite trying `brew cask zap intellij-idea-ce && brew cask install intellij-idea-ce`. The missing icon has persisted through one reboot so far.

<details>
 <summary>Here's my <code>brew cask doctor</code> output</summary>

```shellsession
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.5.0
caskroom/homebrew-cask (git revision f7c5e2; last commit 2018-01-21)
==> macOS
10.13.2
==> SIP
Enabled
==> Java
1.8.0_162, 1.8.0_102, 1.8.0_20, 1.7.0_40, 1.7.0_10, 1.7.0_09, 1.6.0_37-b06-434
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (3 files, 746.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3898 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1149 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (175 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/usr/local/bin/bash"
```
</details>

<details>
<summary>and the <code>zap</code> / <code>install</code> log output</summary>

```shellsession
$ brew cask zap intellij-idea-ce && brew cask install intellij-idea-ce
==> Implied "brew cask uninstall intellij-idea-ce"
==> Moving App 'IntelliJ IDEA CE.app' back to '/usr/local/Caskroom/intellij-idea-ce/2017.3.3,173.4301.25/IntelliJ IDEA CE.app'.
==> Dispatching zap stanza
==> Running zap process for intellij-idea-ce; your password may be necessary
==> Trashing files:
~/Library/Application Support/IdeaIC2017.3
~/Library/Caches/IdeaIC2017.3
~/Library/Logs/IdeaIC2017.3
~/Library/Preferences/IdeaIC2017.3
~/Library/Preferences/com.jetbrains.intellij.ce.plist
~/Library/Saved Application State/com.jetbrains.intellij.ce.savedState
==> Removing all staged versions of Cask 'intellij-idea-ce'
==> Satisfying dependencies
==> Downloading https://download.jetbrains.com/idea/ideaIC-2017.3.3.dmg
Already downloaded: /Users/bholt/Library/Caches/Homebrew/Cask/intellij-idea-ce--2017.3.3,173.4301.25.dmg
==> Verifying checksum for Cask intellij-idea-ce
==> Installing Cask intellij-idea-ce
==> Moving App 'IntelliJ IDEA CE.app' to '/Applications/IntelliJ IDEA CE.app'.
🍺  intellij-idea-ce was successfully installed!
```
</details>

**Comment by commitay** [comment]
> won't come back, despite trying brew cask zap intellij-idea-ce && brew cask install intellij-idea-ce

`zap && install` is how I reproduced the issue, it doesn't fix it.

I had to run this to fix the icon:
```
defaults write com.apple.dock ResetLaunchPad -bool true; killall Dock
```
but it will completely reset the Launchpad.

**Comment by commitay** [comment]
I can reproduce this with several apps, just not reliably. The conditions when it will occur seems to be more or less random. Reproducing the issue, rolling back the VM and rerunning the same command will sometimes work but it usually doesn't.

I think any fix for this that has Cask messing around with Launchpad settings would be overly complicated with the potential to 💥 💥 .

Emulating the old behaviour of deleting the `app` while still preserving a copy in `/Caskroom` to be restored in case of upgrade issues may be the simplest solution, just not a very elegant one.

https://github.com/Homebrew/brew/pull/3715

**Comment by lawkai** [comment]
I have this exact same issue with my intellij-idea-ce. I am not sure if there is any command that can fix it. But the way I fixed this is by doing the following:

1) restart in safe mode. (hold down shift-key and reboot)
2) login to safe mode. (you should see your icon reappear under safe mode)
3) restart as normal. Icon should reappear after you login again.

Hope this help.

**Comment by wickles** [comment]
I am still getting the bad behavior on 10.13.3 with the patch. I think the only way to definitively avoid this is to overwrite the app in-place. I believe that is how Sparkle handles things.

**Comment by commitay** [comment]
> I am still getting the bad behavior on 10.13.3 with the patch.

Were these app icons already broken? The patch won't fix them.

I've been using the patch for a month and I haven't been able to reproduce any issues.

**Comment by wickles** [comment]
No, I made sure to reboot and fix all the remaining broken icons after the patch was pushed. After finding a broken icon this morning I chose some apps to upgrade, checked that their icons were fine, and then found one of them was broken after upgrading. 

It would be good to hear more from other users if anyone else is still having this issue.

**Comment by commitay** [comment]
Which Cask was broken? I'll try to reproduce.

**Comment by wickles** [comment]
Calibre and Zotero most recently, post-patch. Firefox and Atom before the patch, so you could try those too.

**Comment by commitay** [comment]
Unable to reproduce and no new reports.
